when@dev:
    web_profiler_wdt:
        resource: '../../vendor/symfony/web-profiler-bundle/Resources/config/routing/wdt.php'
        type: php
        prefix: /_wdt

    web_profiler_profiler:
        resource: '../../vendor/symfony/web-profiler-bundle/Resources/config/routing/profiler.php'
        type: php
        prefix: /_profiler
